const icons = [
    { id: 'smile' },
    { id: 'sad'},
    { id: 'facepalm' },
    { id: 'laugh' },
    { id: 'like' },
    { id: 'xd' },
    { id: 'cool' },
    { id: 'unamused' },
    { id: 'hysterical' },
    { id: 'upsidedownface' },
    { id: 'loudlycrying' },
    { id: 'sweat' },
    { id: 'tongueout' },
    { id: 'whew' },
    { id: 'kiss' },
    { id: 'angryface' },
    { id: 'worry' },
    { id: 'lipssealed' },
    { id: 'devil' },
    { id: 'swear' },
    { id: 'headbang' },
    { id: 'ttm' },
    { id: 'party' },
    { id: 'clap' },
    { id: 'wait' },
    { id: 'punch' },
    { id: 'fire' },
    { id: 'heart' },
    { id: 'finger' },
    { id: 'mooning' },
    { id: 'smoke' },
    { id: 'sheep' },
    { id: 'tauri' },
    { id: 'poop' },
    { id: 'ontheloo' },
];


export default icons;